# https://VookiImageViewer.cz

language: cpp
os:
  - linux
  - osx

sudo: required
dist: trusty

compiler:
  - clang
  - gcc

env:
  matrix:
    - QT=59 BREW=@5.9 PPA=beineri/opt-qt593-trusty

before_install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get update -qq'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get install qt$QT-meta-minimal cmake libraw-dev'
  - '[ "$TRAVIS_OS_NAME" != linux ] || export CMAKE_PREFIX_PATH=/opt/qt$QT/'
  # Ugly hack (next 2 lines) to workaround the host OS misconfiguration while using clang.
  - '[[ "$TRAVIS_OS_NAME" != linux  || "$CXX" != clang++ ]] || sudo apt-get install libc++-dev'
  - '[[ "$TRAVIS_OS_NAME" != linux  || "$CXX" != clang++ ]] || export CXX="clang++ -stdlib=libc++"'

  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt$BREW'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'
  - '[ "$TRAVIS_OS_NAME" != osx ] || export CMAKE_PREFIX_PATH=/usr/local/opt/qt/'

  - qmake -v
  - cmake --version

script:
  - '[ "$TRAVIS_OS_NAME" != linux ] || cd build/cmake/unix'
  - '[ "$TRAVIS_OS_NAME" != osx ] || cd build/cmake/mac'
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ../../
  - make
